name: emplooo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  dartz: ^0.10.1
  lottie: ^2.0.0
  page_transition: "^2.1.0"
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  http: 
  intl: 
  menu_button: ^1.4.2+1
  shared_preferences: ^2.2.2
  curved_navigation_bar: ^1.0.3
  flutter_bloc: ^8.1.2
  flutter_slider_drawer: ^2.1.3
  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter_animate: ^4.5.0
  animated_widgets: ^1.1.0
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  webview_flutter: ^4.5.0
  flutter_map: ^6.1.0
  url_launcher: ^6.1.14
  another_flushbar: ^1.12.30
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: "Roboto"
      fonts:
        - asset: assets/Roboto-Regular.ttf